FROM node:20 as build-stage

COPY package.json .
COPY package-lock.json .

RUN npm ci

COPY . .

RUN npm run build

#=======================================

FROM node:alpine

RUN npm install -g serve

COPY --from=build-stage /build .

ENTRYPOINT ["serve", "-s", ".","-l","3000"]
CMD []

